#!/bin/bash -e

EPICS_SOURCE="$1"
PROJECT_BINARY_DIR="`pwd`"
EPICS_BASE="${PROJECT_BINARY_DIR}/epics-base"
mkdir -p "${EPICS_BASE}"

makeLink() {
   mkdir -p `dirname "${EPICS_BASE}/$1"`
   ln -sfn "${EPICS_SOURCE}/$1" "${EPICS_BASE}/$1"
}
export -f makeLink
export PROJECT_BINARY_DIR
export EPICS_SOURCE
export EPICS_BASE

if [ ! -f "${PROJECT_BINARY_DIR}/epicsBaseSourceLinked" ]; then
  cd "${EPICS_SOURCE}/"
  echo "Symlinking epics base source..."
  find -type f -exec bash -c "makeLink {}" \;
  touch "${PROJECT_BINARY_DIR}/epicsBaseSourceLinked"
fi

echo "Starting the epics build..."
cd "${EPICS_BASE}"
make -j5 USR_CFLAGS=-w USR_CXXFLAGS=-w

EPICS_ARCH=`grep "^ARCH=" "${EPICS_BASE}/lib/pkgconfig/epics-base.pc" | sed -e 's/^ARCH=//'`

mkdir -p "${PROJECT_BINARY_DIR}/libs"
cp "${PROJECT_BINARY_DIR}/epics-base/lib/${EPICS_ARCH}/"*.a "${PROJECT_BINARY_DIR}/libs"
chmod u+w -R "${PROJECT_BINARY_DIR}/libs"

